language: en
pipeline:
- name: WhitespaceTokenizer
  case_sensitive: false
- name: RegexFeaturizer
- name: CRFEntityExtractor
  case_sensitive: false
- name: EntitySynonymMapper
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
policies:
- name: MemoizationPolicy
- name: MappingPolicy
- name: EmbeddingPolicy
- name: FormPolicy
- name: TwoStageFallbackPolicy
